[package]
name = "openid-connect-rs"
version = "0.1.0"
authors = ["delbertbeta <delbertbeta@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
diesel = { version = "1.4.4", features = ["sqlite"] }
dotenv = "0.15.0"
